### PR TITLE
Get ready for update system

### PR DESCRIPTION
**Pull request by JasonTheKitten**
Also adds graphical installer

Note that it currently only works correctly with my repo.
On other repos you will have to run it multiple times to download all files
It will work correctly when you merge it though

### CODE REVIEW

**Comment by nothjarnan** [comment]
To be quite honest, the installer that we currently have in *this* repo is perfectly fine and doesn't really need changes.

**Comment by JasonTheKitten** [comment]
I've tested mine
I'm planning on a new version system, and this will be the installer needed for it.
The current installer will not work with my version system

As soon as you merge the PR, my installer will work with _this_ repo

In addition, my installer contains other features:

- It is graphical
- Choose any branch
- Choose any fork that supports it, as soon as they are created
- As I said, will work with my planned versioning system

**Comment by JasonTheKitten** [comment]
I've added a table I forgot to add in
Here is why:

> This is to set up newer versions upon install or update, rather than putting one-time code in sys.lua

Which would take up disk space and make the code ugly

**Comment by nothjarnan** [comment]
I have different but similar ideas for the Axiom update system, incorporating the ability to revert to a previous version through good ol' branches on Github, similar to how OmniOS does it with the installer.

**Comment by nothjarnan** [comment]
Please make a **new pull request** when the system works properly, doesn't cause a conflict and doesn't have to be run multiple times to install/update Axiom. Thanks.

**Comment by JasonTheKitten** [comment]
> and doesn't have to be run multiple times to install/update Axiom

If you merge the PR, it automatically fixes that

Also, how does it cause conflict?

**Comment by nothjarnan** [comment]
Due to Axiom/programs/stdgui.app and Axiom/sys.lua.

**Comment by JasonTheKitten** [comment]
I fixed this earlier. Someone must of PR'd it.

I've got a better Idea anyways

**Pull request closed without merging**
