### PR TITLE
Fix what I broke

### PR DESCRIPTION
**Pull request by JasonTheKitten**
Undo what's been done

**THIS TIME I ACTUALLY TESTED IT**

### CODE REVIEW

**Comment by nothjarnan** [comment]
It's almost as if you should read through my code very carefully before editing.

**Comment by JasonTheKitten** [comment]
Sorry, I couldn't really access CC at that moment, only [Mimic](gravlann.github.io)

Also, If you attempt to change the value of replicate_to_screen and it does not affect anything, it's cuz I replaced it with true while debugging and forgot to change it back

(Can you tell that I don't contribute to many repos?)

> It's almost as if you should read through my code very carefully before editing.

The code is a huge jumbo ball that needs organized, sorry. Edge is a bit (a lot) neater than the kernel, but still

**Comment by nothjarnan** [comment]
To be fair, my code was never meant to be read by anyone other than myself B)

**Comment by JasonTheKitten** [comment]
Oh, I see now.

**Pull request merged**
