### PR TITLE
Let's try this again

### PR DESCRIPTION
**Pull request by JasonTheKitten**
This shall work

### CODE REVIEW

**Comment by nothjarnan** [comment]
I don't know why you want to add a UI to the installer, still.

**Comment by JasonTheKitten** [comment]
This is also to ready for my update system im gonna add

**Comment by nothjarnan** [comment]
**Why do you want to add a GUI to the installer?**

**Comment by JasonTheKitten** [comment]
Cuz' why not. It also takes less code

**Comment by JasonTheKitten** [comment]
But as for update stuff goes, it makes the file containing info about the current version, runs the license display script, which should be separate from the OS unlike we have it now, and also puts some version info into the repo

**Comment by nothjarnan** [comment]
But the installer that we have now works perfectly fine, and nobody really cares about a fancypants installer with a GUI.

**Comment by JasonTheKitten** [comment]
What about the update system I am going to write? 
The installer has some important snippets of code, particularly this part:
`local h = fs.open("Axiom/version.0", "w")`
`h.write(textutils.serialize({branch = br, fork = fr, ver = loadURL("https://raw.githubusercontent.com/"..fr.."/"..br.."/CurVersion")}))`
`h.close()`

`textutils.unserialize("function(isInstalling) "..loadURL("https://raw.githubusercontent.com/"..fr.."/"..br.."/onUpdate.lua").." end")(true)`

**Pull request closed without merging**
