### PR TITLE
Update

### PR DESCRIPTION
**Pull request by JasonTheKitten**
update

### CODE REVIEW

**Comment by nothjarnan** [comment]
Looks good. I'd like it if you make install.lua actually install as well.

**Review by nothjarnan — CHANGES_REQUESTED** [review]
installer.lua should actually install, please.

**Comment by JasonTheKitten** [comment]
There you go
`wget https://raw.githubusercontent.com/JasonTheKitten/axiom-opensource/master/install.lua install`
'install'

**Comment by nothjarnan** [comment]
That's not what I meant. I mean more like, fetch the files off of github and install them onto the computer.

**Comment by nothjarnan** [comment]
OK, one question before I merge. 

Why do you format the filesystem **AFTER** you've fetched all the required files?

EDIT: All you have to do is swap line 29 and 30.

**Comment by nothjarnan** [comment]
Nevermind. Read a bit into the code and looks OK. Merging.

**Comment by nothjarnan** [comment]
Turns out that the installer was broken anyway, thus has been fixed.

**Pull request merged**
